name: wlbot CI Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Run wlbot CI Testing
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm test