name: CI Testing & Coverage

on:
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Determine PR Number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: Install Dependencies
        run: npm ci
      - name: Execute UTs
        run: npm run test-ci
      - name: Report Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            annotations: none
            custom-title: CI Testing Coverage
            prnumber: ${{ steps.findPr.outputs.number }}
            test-script: npm run test:ci
            