name: CI Testing & Coverage

on:
  pull_request:
    branches: [ "main" ]

jobs:
  jobs:
  base_branch_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      
      - name: Use Node.js Latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests & Generate Coverage
        run: npm test

      - name: Upload Code Coverage for Bash Branch
        uses: actions/upload-artifact@v3
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info

  checks:
    runs-on: ubuntu-latest
    needs: base_branch_coverage
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      
      - name: Use Node.js Latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Download Code Coverage Report from Base Branch
        uses: actions/download-artifact@v3
        with:
          name: ref-lcov.info

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests & Generate Coverage
        run: npm test

      #  Compares two code coverage files and generates report as a comment
      - name: Generate Code Coverage Report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./lcov.info"
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
            